name: basic workflow

on:
  push:
    branches: [ "main" ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - name: set up sython
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: install requiremets
        run: pip install -r requirements.txt

      - name: Tests
        run: |
          coverage run -m pytest tests/
          coverage report -m --fail-under=70
          coverage xml -o coverage.xml

      - name: Upload coverage report
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: coverage.xml 



build:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: —Åheckout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }} 

      - name: set up sython
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: install requirements
        run: pip install -r requirements.txt

      - name: Get Workflow Status Badge
        id: badge
        uses: jossef/workflow-status-badge@v2
        with:
          workflow: ${{ github.workflow }}
          branch: ${{ github.head_ref }}
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Update README with Badge
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          file_pattern: README.md
          commit_message: "Add build status badge to README"
          push_options: "origin ${{ github.head_ref }}"
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.head_ref }}
          create_new_branch: false
          update_remote_origin: true           
  