name: Test and Build

on:
  pull_request:
    branches: [ "develop" ]

permissions:
  contents: write
  pull-requests: write

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install requirements
        run: pip install -r requirements.txt

      - name: Run Tests with pytest and coverage
        run: |
          coverage run -m pytest tests/
          coverage report -m --fail-under=70
          coverage xml -o coverage.xml

      - name: Upload coverage report
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: coverage.xml

  build:
    needs: test
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Build step
      run: |
        echo "Building the application..."
        
    - name: Check for badge
      id: check_badge
      run: |
        if ! grep -q "!\[CI/CD Pipeline\]" README.md; then
          echo "update_badge=true" >> $GITHUB_OUTPUT
        else
          echo "update_badge=false" >> $GITHUB_OUTPUT
        fi
        
    - name: Update README
      if: steps.check_badge.outputs.update_badge == 'true'
      run: |
        echo "![CI/CD Pipeline](https://github.com/${{ github.repository }}/actions/workflows/test-and-build.yml/badge.svg)" > temp_readme
        cat README.md >> temp_readme
        mv temp_readme README.md
        
    - name: Create PR for README update
      if: steps.check_badge.outputs.update_badge == 'true'
      uses: peter-evans/create-pull-request@v5
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        commit-message: Add build status badge to README
        title: Update README with build status badge
        body: Automatically adding build status badge to README
        branch: update-readme-badge
        base: ${{ github.head_ref || github.ref_name }}
