name: Test and Build

on:
  pull_request:
    branches: [ "develop" ]

permissions:
  contents: write
  pull-requests: write

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install requirements
        run: pip install -r requirements.txt

      - name: Run Tests with pytest and coverage
        run: |
          coverage run -m pytest tests/
          coverage report -m --fail-under=70
          coverage xml -o coverage.xml

      - name: Upload coverage report
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: coverage.xml


  build:
    needs: test
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}

      - name: Build step
        run: echo "Build successful!"

      - name: Update README with build badge
        run: |
          if [ -f README.md ] && ! grep -q "workflow-badge" README.md; then
            echo "![workflow-badge](https://github.com/${{ github.repository }}/actions/workflows/ci.yml/badge.svg)" > temp_readme.md
            echo "" >> temp_readme.md
            cat README.md >> temp_readme.md
            mv temp_readme.md README.md

            git config --local user.email "action@github.com"
            git config --local user.name "GitHub Action"
            git add README.md
            git commit -m "Add workflow badge to README [skip ci]"
            git push
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
